name: Build

on:
  schedule:
    - cron:  '0 2/8 * * *'
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: jorgebg/stateful-action@v0.1
      with:
        branch: state

    - uses: jorgebg/stateful-action@v0.1
      with:
        branch: gh-pages

    - name: Install rawdog
      run: sudo apt-get install rawdog

    - name: Run rawdog
      run: |
        cp .state/state* .
        rawdog -v -d . -uw
        cp ./state* .state/

    - name: Publish
      run: |
        cp ./style.css .gh-pages/
        cp output.html .gh-pages/index.html
